---
- name: Installation et configuration de la suite SDR
  become: true
  become_user: root
  block:
    - name: Remove legacy and conflicting APT packages
      ansible.builtin.apt:
        name: "{{ sdr_packages_to_remove }}"
        state: absent
        purge: true

    - name: Install required build dependencies and SoX
      ansible.builtin.apt:
        name: "{{ sdr_packages_to_install }}"
        update_cache: true
        state: present

    - name: Blacklist the native Linux DVB TV driver
      ansible.builtin.kernel_blacklist:
        name: dvb_usb_rtl28xxu
        state: present

    - name: Check which SDR binaries are already installed
      ansible.builtin.stat:
        path: "{{ item.binary }}"
      loop: "{{ sdr_compilations }}"
      register: sdr_binaries_stat

    - name: Download, compile and install SDR tools from source
      ansible.builtin.include_tasks: compile.yml
      loop: "{{ sdr_binaries_stat.results }}"
      when: not compilation_item.stat.exists
      loop_control:
        loop_var: compilation_item
        label: "{{ compilation_item.item.name }}"

    - name: Clean up temporary build source files
      ansible.builtin.file:
        path: "{{ item.dest }}"
        state: absent
      loop: "{{ sdr_compilations }}"
      loop_control:
        label: "{{ item.dest }}"
