- name: RaspberryPi-Setup
  hosts: RaspberryPi
  gather_facts: false
  become: true
  become_user: root
  roles:
    - role: standard
      tags: ['std']
    - role: multitor
      tags: ['multitor']
    - role: rfid
      tags: ['rfid']
    - role: jackit
      tags: ['jackit']
    - role: wifi
      tags: ['wifi']
    - role: display
      tags: ['display', 'never']
