- hosts: RaspberryPi
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - role: standard
      tags: ['setup']
    - role: multitor
      tags: ['multitor']
    - role: RFID
      tags: ['rfid']
    - role: jackit
      tags: ['jackit']
    - role: hacking
      tags: ['hacking']
