- name: RaspberryPi-Setup
  hosts: RaspberryPi
  gather_facts: true
  become: true
  become_user: atao
  roles:
    - role: standard
      tags: ['standard']
    - role: docker
      tags: ['docker']
    - role: multitor
      tags: ['multitor']
    - role: rfid
      tags: ['rfid']
    - role: jackit
      tags: ['jackit']
    - role: wifi
      tags: ['wifi']
    - role: display
      tags: ['display', 'never']
    - role: container
    - role: web
      tags: ['web']
