- name: RaspberryPi-Setup
  hosts: RaspberryPi
  gather_facts: true
  become: true
  become_user: atao
  roles:
    - role: container
    - role: display
      tags: ['display', 'never']
    - role: docker
      tags: ['docker']
    - role: jackit
      tags: ['jackit', 'never']
    - role: proxy
      tags: ['proxy']
    - role: rfid
      tags: ['rfid']
    - role: standard
      tags: ['standard', 'std']
    - role: web
      tags: ['web']
    - role: wifi
      tags: ['wifi']
