- name: Packages installation
  become: yes
  apt:
    name: "{{ apt_packages }}"
    update_cache: yes

# - name: Git clone hcxtools
#   become_user: root
#   git:
#     repo: "https://github.com/ZerBea/hcxtools.git"
#     dest: "/home/{{ lookup('env', 'USER') }}/hcxtools"
#     clone: yes

# - name: Install hcxtools
#   become_user: root
#   shell: make
#   args:
#     chdir: "/home/{{ lookup('env', 'USER') }}/hcxtools"

# - name: Git clone hcxtools
#   become_user: root
#   git:
#     repo: "https://github.com/ZerBea/hcxdumptool.git"
#     dest: "/home/{{ lookup('env', 'USER') }}/hcxdumptool"
#     clone: yes

# - name: Install hcxdumptool
#   become_user: root
#   shell: make
#   args:
#     chdir: "/home/{{ lookup('env', 'USER') }}/hcxdumptool"

- name: Install Bettercap
  become_user: root
  shell: "go get -u github.com/bettercap/bettercap"
