- name: Packages installation
  become: yes
  apt:
    name: "{{ apt_packages }}"
    update_cache: yes

- name: Git clone hcxtools
  become_user: root
  git:
    repo: "https://github.com/ZerBea/hcxtools.git"
    dest: "$PWD/hcxtools"
    clone: yes

- name: Install hcxtools
  become_user: root
  shell: make
  args:
    chdir: "$PWD/hcxtools"

- name: Remove hcxtools Git folder
  become_user: root
  file:
    path: "$PWD/hcxtools"
    state: absent

- name: Git clone hcxtools
  become_user: root
  git:
    repo: "https://github.com/ZerBea/hcxdumptool.git"
    dest: "$PWD/hcxdumptool"
    clone: yes

- name: Install hcxdumptool
  become_user: root
  shell: make
  args:
    chdir: "$PWD/hcxdumptool"

- name: Remove hcxdumptool Git folder
  become_user: root
  file:
    path: "$PWD/hcxdumptool"
    state: absent
