- name: Git clone jackit
  become: true
  become_user: root
  git:
    repo: https://github.com/insecurityofthings/jackit.git
    dest: /home/{{ lookup('env', 'USER') }}/jackit
    clone: true

- name: Install requirements
  become: true
  become_user: root
  pip:
    requirements: /home/{{ lookup('env', 'USER') }}/jackit/requirements.txt
    executable: pip3

- name: Install jackit
  become: true
  become_user: root
  shell: python3 setup.py install
  args:
    chdir: /home/{{ lookup('env', 'USER') }}/jackit/
