- name: Git clone jackit
  ansible.builtin.git:
    repo: https://github.com/insecurityofthings/jackit.git
    dest: "{{ ansible_facts['env']['HOME'] }}/jackit"
    clone: true

- name: Install requirements
  become: true
  become_user: root
  ansible.builtin.pip:
    requirements: "{{ ansible_facts['env']['HOME'] }}/jackit/requirements.txt"

- name: Install jackit
  ansible.builtin.command: python3 setup.py install
  args:
    chdir: "{{ ansible_facts['env']['HOME'] }}/jackit"