- name: Git clone jackit
  become: true
  become_user: root
  git:
    repo: https://github.com/insecurityofthings/jackit.git
    dest: /root/jackit
    clone: true

- name: Install requirements
  become: true
  become_user: root
  pip:
    requirements: /root/jackit/requirements.txt
    executable: pip3

- name: Install jackit
  become: true
  become_user: root
  shell: python3 /root/jackit/setup.py install