- name: Git clone jackit
  become: yes
  become_user: root
  git:
    repo: https://github.com/insecurityofthings/jackit.git
    dest: /root/jackit
    clone: yes

- name: Install jackit
  become: yes
  become_user: root
  pip:
    requirements: /root/jackit/requirements.txt
    executable: pip3
