- name: Packages installation
  become: yes
  apt:
    name: "{{ apt_packages }}"
    update_cache: yes

- name: Download std.keys from MifareClassicTool
  get_url:
    url: "https://raw.githubusercontent.com/ikarus23/MifareClassicTool/master/\
         Mifare%20Classic%20Tool/app/src/main/assets/key-files/std.keys"
    dest: /home/{{ lookup('env', 'USER') }}/std.keys
    force: yes

- name: Download extended-std.keys from MifareClassicTool
  get_url:
    url: "https://raw.githubusercontent.com/ikarus23/MifareClassicTool/master/\
         Mifare%20Classic%20Tool/app/src/main/assets/key-files/extended-std.keys"
    dest: /home/{{ lookup('env', 'USER') }}/extended-std.keys
    force: yes
 
- name: Download mct2dmp from bm-mifare-classic
  get_url:
    url: "https://github.com/blogmotion/bm-mifare-classic/raw/master/\
         conversion/mct2dmp%20-%20bash%20version/mct2dmp.sh"
    dest: /home/{{ lookup('env', 'USER') }}/mct2dmp.sh
    force: yes
