- name: Packages installation
  become: true
  apt:
    name: "{{ apt_packages }}"
    update_cache: true
    autoremove: true

- name: Install python 3 packages
  pip:
    name: "{{ pip_packages }}"
    executable: pip3

- name: Vim config file
  copy:
    dest: "/home/{{ lookup('env', 'USER') }}/.vimrc"
    content: |
      set mouse-=a
      syntax enable
