---
- name: Packages installation
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: true
    autoremove: true

- name: Deploy .vimrc from template
  ansible.builtin.template:
    src: vimrc.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/.vimrc"
    owner: "{{ ansible_facts['env']['LOGNAME'] }}"
    group: "{{ ansible_facts['env']['LOGNAME'] }}"
    mode: '0644'

- name: Add managed aliases block to .bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    block: |
      {% for alias in bashrc_aliases %}
      {{ alias }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - aliases"
    insertafter: EOF
    create: yes

- name: Ensure other custom lines exist in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    regexp: '^# Custom Ansible config'
    line: "# Custom Ansible config"
    insertafter: EOF
    state: present
