- name: Packages installation
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: true
    autoremove: true

- name: Vim config file
  ansible.builtin.copy:
    dest: "{{ ansible_facts['env']['HOME'] }}/.vimrc"
    content: |
      set mouse-=a
      set paste
      syntax enable
    mode: "644"
