---
- name: Container portainer/portainer-ce:latest
  block:
   - name: Create a volume portainer_data
     become: true
     become_user: root
     community.docker.docker_volume:
      name: portainer_data
   - name: Create container portainer-ce
     become: true
     become_user: root
     community.docker.docker_container:
      name: portainer
      image: portainer/portainer-ce
      state: started
      recreate: false
      pull: true
      detach: true
      restart_policy: "always"
      ports:
       - "8000:8000"
       - "9443:9443"
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data
  tags: portainer

- name: Container jlesage/jdownloader-2
  become: true
  become_user: root
  community.docker.docker_container:
   name: jdownloader-2
   image: jlesage/jdownloader-2
   state: started
   recreate: false
   pull: true
   detach: true
   auto_remove: true
   ports:
    - "5800:5800"
   volumes:
    - "{{ ansible_facts['env']['HOME'] }}/jdownloader:/config"
    - /mnt:/output
   env:
    "JDOWNLOADER_HEADLESS": "1"
  tags: jd2
