---
- name: Container portainer/portainer-ce:latest
  block:
   - name: Create volume portainer_data
     become: true
     become_user: root
     community.docker.docker_volume:
      name: portainer_data
   - name: Create container portainer-ce
     become: true
     become_user: root
     community.docker.docker_container:
      name: portainer
      image: portainer/portainer-ce
      state: started
      recreate: false
      pull: true
      detach: true
      restart_policy: "always"
      ports:
       - "8000:8000"
       - "9443:9443"
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data
  tags: portainer

- name: Container jlesage/jdownloader-2
  become: true
  become_user: root
  community.docker.docker_container:
   name: jdownloader-2
   image: jlesage/jdownloader-2
   state: started
   recreate: false
   pull: true
   detach: true
   auto_remove: true
   ports:
    - "5800:5800"
   volumes:
    - "{{ ansible_facts['env']['HOME'] }}/jdownloader:/config"
    - /mnt:/output
   env:
    "JDOWNLOADER_HEADLESS": "0"
  tags: jd2

- name: Run rotating Tor HTTP proxy container
  become: true
  become_user: root
  docker_container:
   name: rotating-tor-http-proxy
   image: zhaowde/rotating-tor-http-proxy
   ports:
    - "3128:3128"
    - "4444:4444"
   env:
    TOR_INSTANCES: "5"
    TOR_REBUILD_INTERVAL: "3600"
   restart_policy: always
  tags: proxy

- name: Get list of containers
  become: true
  become_user: root
  command: docker ps -a
  register: docker_containers
  tags: always

- name: Show state of Docker containers
  debug:
   var: docker_containers.stdout_lines
  tags: always
