---
apt_packages:
  - screen
  - htop
  - vim
  - git
  - tree
  - locate
  - nmap
  - sqlmap
  - python3-lxml
  - python3-pip
  - python3-venv
  - unattended-upgrades
  - iptraf
  - mc
  - youtube-dl
  - dnsutils
  - traceroute
  - ansible-lint
  - fail2ban
