---
apt_packages:
  - screen
  - htop
  - vim
  - git
  - tree
  - locate
  - nmap
  - sqlmap
  - python3-venv
  - unattended-upgrades
  - iptraf
  - mc
  - dnsutils
  - traceroute
  - ansible-lint
  - fail2ban

bashrc_aliases:
  - "alias ll='ls -l'"
  - "alias la='ls -la'"
  - "alias lla='ls -lah'"
  - "alias fuck='sudo $(history -p !!)'"