---
- name: Installation requirements
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: true

- name: Git clone Polipo
  ansible.builtin.git:
    repo: https://github.com/jech/polipo.git
    dest: "{{ ansible_facts['env']['HOME'] }}/polipo"
    clone: true

- name: Build Polipo
  ansible.builtin.command: make
  args:
    chdir: "{{ ansible_facts['env']['HOME'] }}/polipo"

- name: Remove Polipo Git folder
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/polipo"
    state: absent

- name: Install hpts from npm
  become: true
  become_user: root
  community.general.npm:
    name: http-proxy-to-socks
    global: true

- name: Git clone multitor
  ansible.builtin.git:
    repo: https://github.com/trimstray/multitor.git
    dest: "{{ ansible_facts['env']['HOME'] }}/multitor"
    clone: true

- name: Setup multitor
  ansible.builtin.command: >-
    {{ ansible_facts['env']['HOME'] }}/multitor/setup.sh install

- name: Send file - check_multitor.py
  ansible.builtin.copy:
    src: scripts/check_multitor.py
    dest: "{{ ansible_facts['env']['HOME'] }}/check_multitor.py"
    mode: '755'
    force: true
    owner: "{{ ansible_facts['env']['LOGNAME'] }}"
    group: "{{ ansible_facts['env']['LOGNAME'] }}"

- name: Send file - run_multitor.sh
  ansible.builtin.copy:
    src: scripts/run_multitor.sh
    dest: "{{ ansible_facts['env']['HOME'] }}/run_multitor.sh"
    mode: '755'
    force: true
    owner: "{{ ansible_facts['env']['LOGNAME'] }}"
    group: "{{ ansible_facts['env']['LOGNAME'] }}"
