- name: Installation requirements
  become: yes
  apt:
    name: "{{ apt_packages }}"
    update_cache: yes

- name: Git clone Polipo
  git:
    repo: https://github.com/jech/polipo.git
    dest: "{{ repo_polipo }}"
    clone: yes

- name: Build Polipo
  shell: make
  args:
    chdir: "{{ repo_polipo }}"

- name: Add Polipo to PATH
  copy:
    src: "{{ repo_polipo }}/polipo"
    dest: /usr/bin/polipo
    mode: '755'
    force: yes
    remote_src: yes

- name: Remove Polipo Git folder
  file:
      path: "{{ repo_polipo }}"
      state: absent

- name: Install hpts from npm
  become: yes
  npm:
    name: http-proxy-to-socks
    global: yes

- name: Git clone multitor
  become: yes
  git:
    repo: https://github.com/trimstray/multitor.git
    dest: /root/multitor
    clone: yes

- name: Setup multitor
  become: yes
  command: /root/multitor/setup.sh install
   
- name: Send file - check_multitor.py
  become: yes
  copy:
    src: Scripts/check_multitor.py
    dest: /root/check_multitor.py
    mode: '755'
    force: yes
    
- name: Send file - run_multitor.sh
  become: yes
  copy:
    src: Scripts/run_multitor.sh
    dest: /root/run_multitor.sh
    mode: '755'
    force: yes
