---
- name: Installation requirements
  become: true
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: true

- name: Git clone Polipo
  ansible.builtin.git:
    repo: https://github.com/jech/polipo.git
    dest: "{{ repo_polipo }}"
    clone: true

- name: Build Polipo
  ansible.builtin.shell: make
  args:
    chdir: "{{ repo_polipo }}"

- name: Add Polipo to PATH
  ansible.builtin.copy:
    src: "{{ repo_polipo }}/polipo"
    dest: /usr/bin/polipo
    mode: '755'
    force: true
    remote_src: true

- name: Remove Polipo Git folder
  file:
    path: "{{ repo_polipo }}"
    state: absent

- name: Install hpts from npm
  become: true
  community.general.npm:
    name: http-proxy-to-socks
    global: true

- name: Git clone multitor
  become: true
  ansible.builtin.git:
    repo: https://github.com/trimstray/multitor.git
    dest: "/home/{{ lookup('env', 'USER') }}/multitor"
    clone: true

- name: Setup multitor
  become: true
  ansible.builtin.command: /home/{{ lookup('env', 'USER') }}/multitor/setup.sh install

- name: Send file - check_multitor.py
  become: true
  ansible.builtin.copy:
    src: scripts/check_multitor.py
    dest: /home/{{ lookup('env', 'USER') }}/check_multitor.py
    mode: '755'
    force: true

- name: Send file - run_multitor.sh
  become: true
  ansible.builtin.copy:
    src: scripts/run_multitor.sh
    dest: /home/{{ lookup('env', 'USER') }}/run_multitor.sh
    mode: '755'
    force: true
