---
- name: Packages installation
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: true
    autoremove: true

- name: Check if certbot already installed
  ansible.builtin.stat:
      path: /snap/bin/certbot
  register: certbot

- name: Install certbot
  become: true
  become_user: root
  community.general.snap:
    name: certbot
    classic: true
  when: not certbot.stat.exists

- name: Link certbot
  become: true
  become_user: root
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
    force: true
  when: not certbot.stat.exists
