- name: Uninstall all conflicting packages with Docker
  ansible.builtin.apt:
    name: "{{ old_packages }}"
    state: absent

- name: Install Docker packages
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: true

- name: Check install script exists
  ansible.builtin.stat:
    path: get-docker.sh
  register: stat_result

- name: Download docker install script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: get-docker.sh
  when: stat_result.stat.exists

- name: Run install script
  ansible.builtin.command:
    argv:
      - sh
      - get-docker.sh
  when: stat_result.stat.exists

- name: Verify docker installation
  command: docker -v
  register: docker_version

- name: Docker version
  debug:
    var: docker_version.stdout_lines

- name: Remove script
  file:
    path: get-docker.sh
    state: absent
