- name: Uninstall all conflicting packages with Docker
  ansible.builtin.apt:
    name: "{{ old_packages }}"
    state: absent

- name: Install the Docker packages
  become: true
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: true

- name: Add folder keyrings
  ansible.builtin.command: sudo install -m 0755 -d /etc/apt/keyrings

- name: Add gpg key for Docker repository
  ansible.builtin.command: >-
    curl -fsSL https://download.docker.com/linux/debian/gpg |
    sudo gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Set rights key file
  ansible.builtin.command: sudo chmod a+r /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  ansible.builtin.command: >-
    echo "deb [arch="$(dpkg --print-architecture)"
    signed-by=/etc/apt/keyrings/docker.gpg]
    https://download.docker.com/linux/debian
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" |
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install the Docker packages
  become: true
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    update_cache: true

- name: Run container jlesage/jdownloader-2
  community.docker.docker_container:
    name: jdownloader-2
    image: jlesage/jdownloader-2
    state: present
    recreate: true
    ports:
      - "5800:5800"
    volumes:
      - /home/{{ lookup('env', 'USER') }}/jdownloader:/config
      - /home/{{ lookup('env', 'USER') }}:/output
