---
- name: Uninstall all conflicting packages with Docker
  ansible.builtin.apt:
    name: "{{ old_packages }}"
    state: absent

- name: Install Docker packages
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    update_cache: true

- name: Download docker install script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: "{{ ansible_facts['env']['HOME'] }}/get-docker.sh"

- name: Run install script
  ansible.builtin.command:
    argv:
      - sh
      - "{{ ansible_facts['env']['HOME'] }}/get-docker.sh"

- name: Verify docker installation
  command: docker -v
  register: docker_version

- name: Docker version
  debug:
    var: docker_version.stdout_lines

- name: Remove script
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/get-docker.sh"
    state: absent
