name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@7e35065f65237636fd6bf913c2dc2b74784497ed
      with:
        targets: "./"
        override-deps: |
#          ansible==2.9
          ansible-lint==4.3.7
        args: "-q"
