name: Ansible Lint

on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
          
    - name: Install ansible, ansible-lint, yamllint
      run: pip3 install yamllint ansible ansible-lint

    - name: ansible-lint changed roles
      continue-on-error: true
      run: ansible-lint /home/runner/work/raspberrypi-setup/raspberrypi-setup/playbook.yml
