name: Ansible Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: ansible check with debian:buster
      # replace "master" with any valid ref
      uses: roles-ansible/check-ansible-debian-buster-action@master
      with:
        targets: "./"
